### ISSUE TITLE
カテゴリー表示部分のclassを全カテゴリー共通のスタイルに修正

### ISSUE THREAD

**Issue by mypacecreator** [wp-standard-desgin-book/wp_standard_design_book#23]
現在、

`<span class="categories-links info"><a href="#" rel="category">新メニュー情報</a></span>`
`<span class="categories-links limited"><a href="#" rel="category">スタッフ日記</a></span>`

などのように、infoやlimitedといったclass名にスタイルが依存しているが、これだと汎用的に使えないので、categories-linksに対してスタイルを当てる形に修正してください。
カテゴリーごとに背景色が変わるといった装飾は必要ありません。

**Comment by 1shiharaT** [comment]
a73bbb9eead795b390f656f3689554d03b5ab35e
修正しました。

**Comment by mypacecreator** [comment]
OK!
