### ISSUE TITLE
single.phpのリンク部分　スタイル調整

### ISSUE THREAD

**Issue by mypacecreator** [wp-standard-desgin-book/wp_standard_design_book#24]
the_post_navigation()タグで前後記事へのリンクを出力するようにしたら、ちょっとスタイルがズレてしまうので調整お願いします。
![_ozone_cafe_-_2015-01-18_19 35 40](https://cloud.githubusercontent.com/assets/3164205/5792079/2fd5dd08-9f49-11e4-8ab2-4436c9fef848.png)

**Comment by mypacecreator** [comment]
`.entry-meta .categories-links a`だけでなく、`.entry-meta .categories-links`も文字色を白にしてください。
![_ozone_cafe_-_2015-01-19_00 04 51](https://cloud.githubusercontent.com/assets/3164205/5792829/cf10200c-9f6e-11e4-8535-1e5383ea201c.png)

**Comment by 1shiharaT** [comment]
a73bbb9eead795b390f656f3689554d03b5ab35e
修正しました。
