### ISSUE TITLE
1カラム用の固定ページテンプレート作成(L16)

### ISSUE THREAD

**Issue by mypacecreator** [wp-standard-desgin-book/wp_standard_design_book#25]
recruit/index.htmlをベースに、one-column.phpを作成するので、1カラムに修正しておいてください。
recruit/form.htmlも1カラムでお願いします。

**Comment by mypacecreator** [comment]
* PCビューの時の.l-one-column .l-mainの幅(max-width)を100%じゃなくてコンテンツ幅と同じ726pxにして、真ん中に寄せる
* .l-one-columnの背景色を白に

**Comment by 1shiharaT** [comment]
951b5fa51346b57a038074822e433c879dcbd564
修正しました。
