### ISSUE TITLE
メールフォーム関連スタイル

### ISSUE THREAD

**Issue by mypacecreator** [wp-standard-desgin-book/wp_standard_design_book#27]
必須マークのスタイル／label要素の幅（radioとかも幅指定がきいちゃう）／このページは1カラムテンプレを適用

![_ozone_cafe_-_2015-01-19_14 30 44](https://cloud.githubusercontent.com/assets/3164205/5796272/374952fa-9fe8-11e4-8ce9-6c6a248f1cd5.png)

**Comment by mypacecreator** [comment]
プラグイン側で幅指定するので、min-width: 70%;はトル

**Comment by 1shiharaT** [comment]
修正し、各テーマに反映させました。

**Comment by mypacecreator** [comment]
確認しました！
