### ISSUE TITLE
パンくず用CSS

### ISSUE THREAD

**Issue by mypacecreator** [wp-standard-desgin-book/wp_standard_design_book#28]
WP SiteManagerのパンくず用スタイルを追加。

**Comment by mypacecreator** [comment]
'''
ul.bread_crumb {
	width: 100%;
	max-width: 1000px;
	margin: 10px auto;
}
ul.bread_crumb li {
	font-size: 0.9em;
	display: inline-block;
}
ul.bread_crumb li.sub:before {
	content:' > ';
}
'''
でそれっぽく。

**Comment by 1shiharaT** [comment]
追加しました！
d3743766d335f95cbfa8291dab8814124c5832fd

**Comment by mypacecreator** [comment]
OK!!
