### ISSUE TITLE
投稿詳細ページのベースHTML

### ISSUE THREAD

**Issue by mypacecreator** [wp-standard-desgin-book/wp_standard_design_book#30]
article02.htmlや、menu02〜08.htmlは消してしまいましたが、L10の再構成に伴い、やっぱり作っておいたほうがよいのでは、、、と思いました。

**Comment by mypacecreator** [comment]
article02.htmlは作成しました。
あと menu02〜08.htmlの作成（復活？）必要。

**Comment by 1shiharaT** [comment]
951b5fa51346b57a038074822e433c879dcbd564

完了しました。
